// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrR-EB1cE1F9OiOFez8HT_C48VIvLe1zk',
    appId: '1:319165775802:web:69090f0b31097701256783',
    messagingSenderId: '319165775802',
    projectId: 'discussit-93231',
    authDomain: 'discussit-93231.firebaseapp.com',
    storageBucket: 'discussit-93231.appspot.com',
    measurementId: 'G-D3VKVPJBX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfAMyXQn0eeIZqMbskVv4644_k0bLnTqk',
    appId: '1:319165775802:android:b7041d8c2a8ed6eb256783',
    messagingSenderId: '319165775802',
    projectId: 'discussit-93231',
    storageBucket: 'discussit-93231.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMFaGV3j8HvU508aoERql9UAQG8xKfqnU',
    appId: '1:319165775802:ios:e31f67d57c0ffb50256783',
    messagingSenderId: '319165775802',
    projectId: 'discussit-93231',
    storageBucket: 'discussit-93231.appspot.com',
    iosClientId: '319165775802-la4s076tgrtb1lind4ueon10fijjg4op.apps.googleusercontent.com',
    iosBundleId: 'com.example.discussit',
  );
}
